// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using Newtonsoft.Json;

namespace InstaMovieBeta.Models.Rovi
{

    public class ControlSet
    {

        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("code")]
        public int Code { get; set; }

        [JsonProperty("messages")]
        public object Messages { get; set; }
    }

}
