// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using InstaMovieBeta;

namespace InstaMovieBeta.Models.Rovi
{

    public class Image
    {

        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonProperty("height")]
        public int Height { get; set; }

        [JsonProperty("width")]
        public int Width { get; set; }

        [JsonProperty("formatid")]
        public int Formatid { get; set; }

        [JsonProperty("author")]
        public string Author { get; set; }

        [JsonProperty("copyrightOwner")]
        public string CopyrightOwner { get; set; }

        [JsonProperty("imageTypeId")]
        public int ImageTypeId { get; set; }

        [JsonProperty("zoomLevel")]
        public object ZoomLevel { get; set; }
    }

}
