// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace InstaMovieBeta.Models.Rovi
{

    public class Parameters
    {

        [JsonProperty("apiKey")]
        public string ApiKey { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }
    }

}
