// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using InstaMovieBeta;

namespace InstaMovieBeta.Models.Rovi
{

    public class Related
    {

        [JsonProperty("similarTo")]
        public SimilarTo[] SimilarTo { get; set; }

        [JsonProperty("isRelatedTo")]
        public IsRelatedTo[] IsRelatedTo { get; set; }

        [JsonProperty("isFollowedBy")]
        public IsFollowedBy[] IsFollowedBy { get; set; }

        [JsonProperty("precededBy")]
        public PrecededBy[] PrecededBy { get; set; }
    }

}
