// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using Newtonsoft.Json;

namespace InstaMovieBeta.Models.Rovi
{

    public class SearchResponse
    {

        [JsonProperty("searchResponse")]
        public SearchDetails Details { get; set; }
    }

}
