// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;


namespace InstaMovieBeta.Models.Rovi.SearchResponseJsonTypes
{

    public class Variant
    {

        [JsonProperty("videoHandle")]
        public VideoHandle VideoHandle { get; set; }

        [JsonProperty("providerTitle")]
        public string ProviderTitle { get; set; }

        [JsonProperty("streamable")]
        public int? Streamable { get; set; }

        [JsonProperty("programLanguage")]
        public string ProgramLanguage { get; set; }

        [JsonProperty("originalProgramId")]
        public object OriginalProgramId { get; set; }

        [JsonProperty("streamableLastUpdateDate")]
        public object StreamableLastUpdateDate { get; set; }

        [JsonProperty("priceoptions")]
        public object Priceoptions { get; set; }

        [JsonProperty("contentUri")]
        public string ContentUri { get; set; }

        [JsonProperty("contentType")]
        public string ContentType { get; set; }
    }

}
