// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using Newtonsoft.Json;

namespace InstaMovieBeta.Models.Rovi.SearchResponseJsonTypes
{

    public class Video
    {

        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("screenshot")]
        public string Screenshot { get; set; }

        [JsonProperty("provider")]
        public string Provider { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }
    }

}
