// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;


namespace InstaMovieBeta.Models.Rovi.MovieInfoJsonTypes
{

    public class Ids
    {

        [JsonProperty("cosmoId")]
        public string CosmoId { get; set; }

        [JsonProperty("movieId")]
        public string MovieId { get; set; }
    }

}
