// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;


namespace InstaMovieBeta.Models.Rovi.MovieInfoJsonTypes
{

    public class Ids3
    {

        [JsonProperty("movieReleaseId")]
        public object MovieReleaseId { get; set; }

        [JsonProperty("releaseId")]
        public string ReleaseId { get; set; }

        [JsonProperty("upcId")]
        public string UpcId { get; set; }
    }

}
