// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using InstaMovieBeta.Models.Rovi.CommonJsonTypes;


namespace InstaMovieBeta.Models.Rovi.MovieInfoJsonTypes
{

    public class Movie
    {

        [JsonProperty("ids")]
        public Ids Ids { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("altTitle")]
        public string AltTitle { get; set; }

        [JsonProperty("altTitles")]
        public AltTitle[] AltTitles { get; set; }

        [JsonProperty("altTitlesUri")]
        public string AltTitlesUri { get; set; }

        [JsonProperty("releaseYear")]
        public string ReleaseYear { get; set; }

        [JsonProperty("rating")]
        public int Rating { get; set; }

        [JsonProperty("duration")]
        public int Duration { get; set; }

        [JsonProperty("directors")]
        public Director[] Directors { get; set; }

        [JsonProperty("countries")]
        public string[] Countries { get; set; }

        [JsonProperty("mpaa")]
        public string Mpaa { get; set; }

        [JsonProperty("flags")]
        public string[] Flags { get; set; }

        [JsonProperty("genres")]
        public Genre[] Genres { get; set; }

        [JsonProperty("attributes")]
        public object Attributes { get; set; }

        [JsonProperty("cast")]
        public Cast[] Cast { get; set; }

        [JsonProperty("castUri")]
        public string CastUri { get; set; }

        [JsonProperty("crew")]
        public Crew[] Crew { get; set; }

        [JsonProperty("crewUri")]
        public string CrewUri { get; set; }

        [JsonProperty("images")]
        public Image[] Images { get; set; }

        [JsonProperty("imagesUri")]
        public string ImagesUri { get; set; }

        [JsonProperty("keywords")]
        public Keyword[] Keywords { get; set; }

        [JsonProperty("keywordsUri")]
        public string KeywordsUri { get; set; }

        [JsonProperty("moods")]
        public Mood[] Moods { get; set; }

        [JsonProperty("moodsUri")]
        public string MoodsUri { get; set; }

        [JsonProperty("related")]
        public Related Related { get; set; }

        [JsonProperty("relatedUri")]
        public string RelatedUri { get; set; }

        [JsonProperty("releases")]
        public Release[] Releases { get; set; }

        [JsonProperty("releasesUri")]
        public string ReleasesUri { get; set; }

        [JsonProperty("review")]
        public Review Review { get; set; }

        [JsonProperty("reviewUri")]
        public string ReviewUri { get; set; }

        [JsonProperty("similar")]
        public Similar[] Similar { get; set; }

        [JsonProperty("similarUri")]
        public string SimilarUri { get; set; }

        [JsonProperty("synopsis")]
        public Synopsis Synopsis { get; set; }

        [JsonProperty("synopsisUri")]
        public string SynopsisUri { get; set; }

        [JsonProperty("themes")]
        public Theme[] Themes { get; set; }

        [JsonProperty("themesUri")]
        public string ThemesUri { get; set; }

        [JsonProperty("tones")]
        public object Tones { get; set; }

        [JsonProperty("tonesUri")]
        public object TonesUri { get; set; }

        [JsonProperty("types")]
        public Type[] Types { get; set; }

        [JsonProperty("typesUri")]
        public string TypesUri { get; set; }

        [JsonProperty("videos")]
        public Video[] Videos { get; set; }

        [JsonProperty("videosUri")]
        public string VideosUri { get; set; }

        [JsonProperty("studio")]
        public string Studio { get; set; }

        [JsonProperty("producedBy")]
        public string[] ProducedBy { get; set; }

        [JsonProperty("releasedBy")]
        public string[] ReleasedBy { get; set; }

        [JsonProperty("distributor")]
        public object Distributor { get; set; }

        [JsonProperty("originCountries")]
        public string[] OriginCountries { get; set; }

        [JsonProperty("schemaVersion")]
        public int SchemaVersion { get; set; }
    }

}
