// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;


namespace InstaMovieBeta.Models.Rovi.MovieInfoJsonTypes
{

    public class Release
    {

        [JsonProperty("ids")]
        public Ids3 Ids { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("studio")]
        public string Studio { get; set; }

        [JsonProperty("rating")]
        public int Rating { get; set; }

        [JsonProperty("formats")]
        public string[] Formats { get; set; }

        [JsonProperty("year")]
        public string Year { get; set; }

        [JsonProperty("hasCommentary")]
        public bool HasCommentary { get; set; }

        [JsonProperty("isPurchasable")]
        public bool IsPurchasable { get; set; }
    }

}
