// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;


namespace InstaMovieBeta.Models.Rovi.MovieInfoJsonTypes
{

    public class Relevance
    {

        [JsonProperty("code")]
        public string Code { get; set; }

        [JsonProperty("value")]
        public double Value { get; set; }
    }

}
