// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;


namespace InstaMovieBeta.Models.Rovi.MovieInfoJsonTypes
{

    public class SearchResponse
    {

        [JsonProperty("meta:id")]
        public string MetaId { get; set; }

        [JsonProperty("controlSet")]
        public ControlSet ControlSet { get; set; }

        [JsonProperty("results")]
        public Result[] Results { get; set; }

        [JsonProperty("totalResultCounts")]
        public int TotalResultCounts { get; set; }
    }

}
