// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace InstaMovieBeta.Models.Rovi.CommonJsonTypes
{

    public class ParentalRating
    {

        [JsonProperty("ratingType")]
        public string RatingType { get; set; }

        [JsonProperty("rating")]
        public string Rating { get; set; }

        [JsonProperty("reasons")]
        public string[] Reasons { get; set; }
    }

}
