// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace InstaMovieBeta.Models.Rovi.CommonJsonTypes
{

    public class Related
    {

        [JsonProperty("similarTo")]
        public SimilarTo[] SimilarTo { get; set; }
    }

}
