// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace InstaMovieBeta.Models.Rovi.CommonJsonTypes
{

    public class Review
    {

        [JsonProperty("review")]
        public string _Review { get; set; }

        [JsonProperty("source")]
        public object Source { get; set; }

        [JsonProperty("language")]
        public string Language { get; set; }

        [JsonProperty("cuttingPositions")]
        public object CuttingPositions { get; set; }
    }

}
