// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using InstaMovieBeta.Models.Rovi.SearchResponseJsonTypes;


namespace InstaMovieBeta.Models.Rovi.CommonJsonTypes
{

    public class Video
    {

        [JsonProperty("ids")]
        public Ids Ids { get; set; }

        [JsonProperty("requestedId")]
        public string RequestedId { get; set; }

        [JsonProperty("seriesIds")]
        public object SeriesIds { get; set; }

        [JsonProperty("masterTitle")]
        public string MasterTitle { get; set; }

        [JsonProperty("secondaryTitle")]
        public string SecondaryTitle { get; set; }

        [JsonProperty("episodeTitle")]
        public object EpisodeTitle { get; set; }

        [JsonProperty("category")]
        public string Category { get; set; }

        [JsonProperty("color")]
        public string Color { get; set; }

        [JsonProperty("lastAirDate")]
        public object LastAirDate { get; set; }

        [JsonProperty("originalAirDate")]
        public object OriginalAirDate { get; set; }

        [JsonProperty("programType")]
        public string ProgramType { get; set; }

        [JsonProperty("releaseYear")]
        public int ReleaseYear { get; set; }

        [JsonProperty("duration")]
        public int Duration { get; set; }

        [JsonProperty("subcategory")]
        public string Subcategory { get; set; }

        [JsonProperty("syndicated")]
        public bool Syndicated { get; set; }

        [JsonProperty("programLanguage")]
        public string ProgramLanguage { get; set; }

        [JsonProperty("partNumber")]
        public object PartNumber { get; set; }

        [JsonProperty("partTotal")]
        public object PartTotal { get; set; }

        [JsonProperty("streamable")]
        public int Streamable { get; set; }

        [JsonProperty("movieRating")]
        public string MovieRating { get; set; }

        [JsonProperty("associatedAlbums")]
        public object AssociatedAlbums { get; set; }

        [JsonProperty("associatedAlbumsUri")]
        public string AssociatedAlbumsUri { get; set; }

        [JsonProperty("associatedTracks")]
        public object AssociatedTracks { get; set; }

        [JsonProperty("associatedTracksUri")]
        public object AssociatedTracksUri { get; set; }

        [JsonProperty("parentalRatings")]
        public ParentalRating[] ParentalRatings { get; set; }

        [JsonProperty("parentalRatingsUri")]
        public string ParentalRatingsUri { get; set; }

        [JsonProperty("starRating")]
        public object StarRating { get; set; }

        [JsonProperty("tvRating")]
        public string TvRating { get; set; }

        [JsonProperty("mpaaRating")]
        public string MpaaRating { get; set; }

        [JsonProperty("cast")]
        public Cast[] Cast { get; set; }

        [JsonProperty("castUri")]
        public string CastUri { get; set; }

        [JsonProperty("crew")]
        public Crew[] Crew { get; set; }

        [JsonProperty("crewUri")]
        public string CrewUri { get; set; }

        [JsonProperty("awards")]
        public object Awards { get; set; }

        [JsonProperty("awardsUri")]
        public object AwardsUri { get; set; }

        [JsonProperty("images")]
        public Image[] Images { get; set; }

        [JsonProperty("imagesUri")]
        public string ImagesUri { get; set; }

        [JsonProperty("clip")]
        public Clip[] Clip { get; set; }

        [JsonProperty("clipUri")]
        public string ClipUri { get; set; }

        [JsonProperty("seasons")]
        public object Seasons { get; set; }

        [JsonProperty("seasonsUri")]
        public object SeasonsUri { get; set; }

        [JsonProperty("variants")]
        public Variant[] Variants { get; set; }

        [JsonProperty("variantsUri")]
        public string VariantsUri { get; set; }

        [JsonProperty("schedule")]
        public string Schedule { get; set; }

        [JsonProperty("scheduleUri")]
        public object ScheduleUri { get; set; }

        [JsonProperty("event")]
        public object Event { get; set; }

        [JsonProperty("eventUri")]
        public object EventUri { get; set; }

        [JsonProperty("keywords")]
        public Keywords Keywords { get; set; }

        [JsonProperty("keywordsUri")]
        public string KeywordsUri { get; set; }

        [JsonProperty("moods")]
        public Mood[] Moods { get; set; }

        [JsonProperty("moodsUri")]
        public string MoodsUri { get; set; }

        [JsonProperty("related")]
        public Related Related { get; set; }

        [JsonProperty("relatedUri")]
        public string RelatedUri { get; set; }

        [JsonProperty("review")]
        public Review Review { get; set; }

        [JsonProperty("reviewUri")]
        public string ReviewUri { get; set; }

        [JsonProperty("synopsis")]
        public Synopsis Synopsis { get; set; }

        [JsonProperty("synopsisUri")]
        public string SynopsisUri { get; set; }

        [JsonProperty("themes")]
        public Theme[] Themes { get; set; }

        [JsonProperty("themesUri")]
        public string ThemesUri { get; set; }

        [JsonProperty("tones")]
        public Tone[] Tones { get; set; }

        [JsonProperty("tonesUri")]
        public string TonesUri { get; set; }

        [JsonProperty("seasonNumber")]
        public object SeasonNumber { get; set; }

        [JsonProperty("seasonSequence")]
        public object SeasonSequence { get; set; }

        [JsonProperty("seriesSequence")]
        public object SeriesSequence { get; set; }

        [JsonProperty("programLanguageCode")]
        public string ProgramLanguageCode { get; set; }

        [JsonProperty("web")]
        public object Web { get; set; }

        [JsonProperty("webUri")]
        public object WebUri { get; set; }

        [JsonProperty("originalTitle")]
        public string OriginalTitle { get; set; }

        [JsonProperty("originCountries")]
        public string[] OriginCountries { get; set; }
    }

}
